version: "3.9"

services:

  redis:
    image: redis:latest
    container_name: "my_redis"
    ports:
      - "6379:6379"


#version: '3.8'
#services:
#  redis:
#    image: redis:6.2-alpine
#    restart: always
#    ports:
#      - '6379:6379'
#    command: redis-server --save 60 1 --loglevel warning --requirepass pass
#    volumes:
#      - ./data:/data
