spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/movieland
  jpa:
#    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true