spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/movieland
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

nbuRatesUrl: https://bank.gov.ua/NBUStatService/v1/statdirectory/exchange